"""Add weather table

Revision ID: 1628c6041b37
Revises: c0963b6b4e04
Create Date: 2023-09-27 16:52:47.489991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1628c6041b37'
down_revision = 'c0963b6b4e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_status',
    sa.Column('last_reported', sa.TIMESTAMP(), nullable=False),
    sa.Column('temperature_in_c', sa.Float(), nullable=False),
    sa.Column('windspeed', sa.Float(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('last_reported')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_status')
    # ### end Alembic commands ###
