CREATE TABLE IF NOT EXISTS station_detail
(
    ID         VARCHAR PRIMARY KEY,
    NAME       VARCHAR NOT NULL,
    SHORT_NAME VARCHAR NOT NULL,
    LAT        REAL    NOT NULL,
    LON        REAL    NOT NULL,
    REGION_ID  VARCHAR NOT NULL,
    CAPACITY   INT
);

CREATE TABLE IF NOT EXISTS station_status
(
    ID VARCHAR NOT NULL,
    BIKES_AVAILABLE INT NOT NULL,
    DOCKS_AVAILABLE INT NOT NULL,
    IS_INSTALLED INT NOT NULL,
    IS_RENTING INT NOT NULL,
    IS_RETURNING INT NOT NULL,
    LAST_REPORTED TIMESTAMP NOT NULL
);